[package]
name = "driver"
version = "0.4.1"
edition = "2021"

[dependencies]
bindings = { path = "../bindings" }
log = { version = "0.4.1" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
#thiserror = { version = "2.0.12" }