[package]
name = "bindings"
version = "0.3.0"
edition = "2024"

[build-dependencies]
bindgen = { version = "0.71.1" }
cc = "1.0"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation-sys = "0.8.7"
core-foundation = "0.10.0"