[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["derive", "default"] }
driver = { path = "../driver" }
razer = { path = "../razer" }
gui = { path = "../gui" }